### ISSUE TITLE
snap refresh -> systemctl: unrecognized option '--now'  on 14.04.1-Ubuntu

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [wekan/wekan-snap#34]
Looks like I can't upgrade wekan anymore, after 
```shell
$ sudo snap refresh wekan

error: cannot perform the following tasks:
- stop of [wekan.caddy] (# systemctl disable --now snap.wekan.caddy.service
systemctl: unrecognized option '--now'
)
- stop of [wekan.caddy] (exit status 1)
```

Current snap:
```shell
$ snap info  wekan
name:      wekan
summary:   The open-source Trello-like kanban
publisher: xet7
license:   unknown
description: |
  Wekan is an open-source and collaborative kanban board application.

  Whether you’re maintaining a personal todo list, planning your holidays with
  some friends, or working in a team on your next revolutionary idea, Kanban
  boards are an unbeatable tool to keep your things organized. They give you a
  visual overview of the current state of your project, and make you productive
  by allowing you to focus on the few items that matter the most.
  Depending on target environment, some configuration settings might need to be
  adjusted.
  For full list of configuration options call:
  $ wekan.help
snap-id: jtpboSYvTCEyHoutkkRo1SI9ioSMOUb3
commands:
  - wekan.database-backup
  - wekan.database-list-backups
  - wekan.database-restore
  - wekan.help
services:
  wekan.mongodb: simple, enabled, active
  wekan:         simple, enabled, active
tracking:        stable
installed:       0.76 (126) 133MB -
refreshed:       2018-02-21 20:29:58 +0100 CET
channels:
  stable:        0.77 (130) 139MB -
  candidate:     0.77 (130) 139MB -
  beta:          0.77 (130) 139MB -
  edge:          0.77 (130) 139MB -
```

**Comment by xet7** [comment]
Huh? AFAIK Wekan snaps are made for Ubuntu 16.04 and newer.

@kubiko 

Do you know about this?

**Comment by h0jeZvgoxFepBQ2C** [comment]
🤷‍♂️ I'm using it without problems until now xD

~Also its somehow surprising that I get the upgrade error, even when the installed version is already 0.77 (and doesnt need to be upgraded?)~

**Comment by xet7** [comment]
I think I should just remove that `--now` text from there, then it should work.

**Comment by xet7** [comment]
I did not find yet where to make the change.

But if this is for Ubuntu 14.04, it should probably use init.d commands like service, not systemctl.

Hopefully @kubiko can figure this out.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Hm, couldn't find too.. Maybe it's a snap bug in general..

**Comment by kubiko** [comment]
This is interesting and could be down to systemd incompatibility on 14.04
I passed this bug to snapd developers, so they can investigate more
@stolowski might know more

**Comment by stolowski** [comment]
This is a bug in snapd, not in this snap. It turns out the version of systemd in 14.04 doesn't support "--now" flag, which snapd passes internally to systemctl if the services are controlled by snapctl start/stop from snap's hooks. We will fix this in snapd. 
In the meantime the only workaround I can think think of is to avoid stopping the service from the hooks via snapctl if possible, they will be stopped and started automatically on refresh anyway and without the problematic flag. I'm sorry for the inconvenience.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Thanks for the response, no problem! :)

**Comment by stolowski** [comment]
This is the proposed fix for snapd: https://github.com/snapcore/snapd/pull/4762

**Comment by xet7** [comment]
@stolowski 

It seems that fix has been merged. Is it released already?

**Comment by xet7** [comment]
@lichtamberg 

Can you try updating your Ubuntu all updates, including snap updates, and testing updating to newest Wekan with `sudo snap refresh` ?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Hm.. I did an apt-get update/upgrade, and then ran sudo snap refresh, but still get the same error message:

```shell
- stop of [wekan.caddy] (# systemctl disable --now snap.wekan.caddy.service
systemctl: unrecognized option '--now'
)
- stop of [wekan.caddy] (exit status 1)
```

**Comment by xet7** [comment]
Ok, it's not fixed yet.

**Comment by stolowski** [comment]
It only landed in master branch which means it should very soon be available if you switch to the core image from the edge channel. But it will take some more weeks before it's in stable release.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Unfortunately there is still no update available for snapd on ubuntu 14.04. Is there an easy fix how I can update wekan without this missing snapd-patch?

**Comment by xet7** [comment]
@lichtamberg 

Do you have Ubuntu 16.04 or Debian 9 or CentOS 7 or newer available somewhere? It would work there.

**Comment by xet7** [comment]
Snap runs in many 64bit Linux versions: https://snapcraft.io

**Comment by h0jeZvgoxFepBQ2C** [comment]
Unfortunately not, I tried to update to 16.04. one time but it failed. Will try it again now.

**Comment by xet7** [comment]
Clean install would work best, for example Debian 9 or Ubuntu 17.10

**Comment by xet7** [comment]
You could also run Wekan in Docker or VirtualBox

**Comment by xet7** [comment]
Or install from source, but that would not get automatic updates etc like snap

**Comment by stolowski** [comment]
If using snapd from beta channel is an option, then see https://forum.snapcraft.io/t/please-help-testing-2-32-in-beta/4696

**Comment by h0jeZvgoxFepBQ2C** [comment]
Ok, after I did an release upgrade on our ubuntu machine (and a complete outage due to upgrade issues and a broken partition table/broken fstab while having some heart attacks) I managed to update snapd 👍 Thanks!
