### ISSUE TITLE
Snap error: snap.wekan.wekan.service: Start request repeated too quickly.

### ISSUE THREAD

**Issue by nomomnom** [wekan/wekan-snap#88]
Hey,

I installed wekan with snap on a new Ubuntu Server 18.10 Virtual Machine. When I want to start the wekan snap service, or the mongodb service, I get following error:
`Apr 18 07:17:49 wekan systemd[1]: snap.wekan.wekan.service: Service RestartSec=100ms expired, scheduling restart.
Apr 18 07:17:49 wekan systemd[1]: snap.wekan.wekan.service: Scheduled restart job, restart counter is at 6.
Apr 18 07:17:49 wekan systemd[1]: Stopped Service for snap application wekan.wekan.
Apr 18 07:17:49 wekan systemd[1]: **snap.wekan.wekan.service: Start request repeated too quickly.**
Apr 18 07:17:49 wekan systemd[1]: snap.wekan.wekan.service: Failed with result 'exit-code'.
Apr 18 07:17:49 wekan systemd[1]: Failed to start Service for snap application wekan.wekan.`

Kernel Info:
Linux wekan 4.18.0-17-generic #18-Ubuntu SMP Wed Mar 13 14:34:40 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Any ideas?

**Comment by xet7** [comment]
Maybe reboot?

**Comment by nomomnom** [comment]
> Maybe reboot?

Nope, still not working....

**Comment by xet7** [comment]
@nomomnom 

Is snap running wekan.wekan and wekan.mongodb?
```
sudo snap services
```
If you need only http, you can change Wekan port from 3001 to 80:
```
sudo snap set wekan port='80'
```
Also set root-url, see https://github.com/wekan/wekan/wiki/Settings

**Comment by nomomnom** [comment]
Nope. If I start both services, they are both running. Shortly after that the snap.wekan.mongodb fails and right after that snap.wekan.wekan also fails.
`sudo snap services` just shows, that both services are enabled but inactive.
I set the port and the root-url. No changes :(

**Comment by xet7** [comment]
What virtual machine this is? Is it on some hosting provider, or some local VirtualBox or VMWare?

**Comment by xet7** [comment]
When it's inactive or not enabled, it's not running. Try:
```
sudo systemctl enable snap.wekan.mongodb
sudo systemctl enable snap.wekan.wekan
sudo systemctl start snap.wekan.mongodb
sudo systemctl start snap.wekan.wekan
sudo snap start wekan
```

**Comment by xet7** [comment]
What does this say?
```
sudo snap logs wekan
```

**Comment by nomomnom** [comment]
The admin that provided the server says the virtualisation is on OpenStack, KVM.
`sudo snap logs wekan` gives me this log data:

`ubuntu@wekan:~$ sudo snap logs wekan.wekan
2019-04-18T10:56:49Z wekan.wekan[12625]:     at Object.onceWrapper (events.js:315:30)
2019-04-18T10:56:49Z wekan.wekan[12625]:     at emitOne (events.js:116:13)
2019-04-18T10:56:49Z systemd[1]: snap.wekan.wekan.service: Main process exited, code=exited, status=1/FAILURE
2019-04-18T10:56:49Z systemd[1]: snap.wekan.wekan.service: Failed with result 'exit-code'.
2019-04-18T10:56:49Z systemd[1]: snap.wekan.wekan.service: Service RestartSec=100ms expired, scheduling restart.
2019-04-18T10:56:49Z systemd[1]: snap.wekan.wekan.service: Scheduled restart job, restart counter is at 5.
2019-04-18T10:56:49Z systemd[1]: Stopped Service for snap application wekan.wekan.
2019-04-18T10:56:49Z systemd[1]: snap.wekan.wekan.service: Start request repeated too quickly.
2019-04-18T10:56:49Z systemd[1]: snap.wekan.wekan.service: Failed with result 'exit-code'.
2019-04-18T10:56:49Z systemd[1]: Failed to start Service for snap application wekan.wekan.
ubuntu@wekan:~$ sudo snap logs wekan
2019-04-18T10:56:49Z wekan.wekan[12625]:     at Object.onceWrapper (events.js:315:30)
2019-04-18T10:56:49Z wekan.wekan[12625]:     at emitOne (events.js:116:13)
2019-04-18T10:56:49Z systemd[1]: snap.wekan.wekan.service: Main process exited, code=exited, status=1/FAILURE
2019-04-18T10:56:49Z systemd[1]: snap.wekan.wekan.service: Failed with result 'exit-code'.
2019-04-18T10:56:49Z systemd[1]: snap.wekan.wekan.service: Service RestartSec=100ms expired, scheduling restart.
2019-04-18T10:56:49Z systemd[1]: snap.wekan.wekan.service: Scheduled restart job, restart counter is at 5.
2019-04-18T10:56:49Z systemd[1]: Stopped Service for snap application wekan.wekan.
2019-04-18T10:56:49Z systemd[1]: snap.wekan.wekan.service: Start request repeated too quickly.
2019-04-18T10:56:49Z systemd[1]: snap.wekan.wekan.service: Failed with result 'exit-code'.
2019-04-18T10:56:49Z systemd[1]: Failed to start Service for snap application wekan.wekan.
`

**Comment by xet7** [comment]
What does this say:
```
sudo snap logs wekan.mongodb
sudo systemctl status snap.wekan.mongodb
```

**Comment by xet7** [comment]
You could also try to reinstall Wekan:
```
sudo snap remove wekan
sudo snap install wekan
```
Is this on OVH or Kimsufi servers? Those have restricted kernels.

**Comment by nomomnom** [comment]
`sudo snap logs wekan.mongodb`:
`2019-04-18T10:48:18Z wekan.mongodb[7295]: DEFAULT_AUTHENTICATION_METHOD= (default value)
2019-04-18T10:48:18Z wekan.mongodb[7295]: mongodb bind options:  --unixSocketPrefix  /var/snap/wekan/current/share --bind_ip 127.0.0.1,10.34.54.247 --port 27019
2019-04-18T10:48:18Z systemd[1]: snap.wekan.mongodb.service: Main process exited, code=exited, status=48/n/a
2019-04-18T10:48:18Z systemd[1]: snap.wekan.mongodb.service: Failed with result 'exit-code'.
2019-04-18T10:48:18Z systemd[1]: snap.wekan.mongodb.service: Service RestartSec=100ms expired, scheduling restart.
2019-04-18T10:48:18Z systemd[1]: snap.wekan.mongodb.service: Scheduled restart job, restart counter is at 5.
2019-04-18T10:48:18Z systemd[1]: Stopped Service for snap application wekan.mongodb.
2019-04-18T10:48:18Z systemd[1]: snap.wekan.mongodb.service: Start request repeated too quickly.
2019-04-18T10:48:18Z systemd[1]: snap.wekan.mongodb.service: Failed with result 'exit-code'.
2019-04-18T10:48:18Z systemd[1]: Failed to start Service for snap application wekan.mongodb.
`
`sudo systemctl status snap.wekan.mongodb` 
says the same as the wekan.wekan service:

` snap.wekan.mongodb.service - Service for snap application wekan.mongodb
   Loaded: loaded (/etc/systemd/system/snap.wekan.mongodb.service; enabled; vendor preset: enable
   Active: failed (Result: exit-code) since Thu 2019-04-18 10:48:18 UTC; 50min ago
  Process: 7295 ExecStart=/usr/bin/snap run wekan.mongodb (code=exited, status=48)
 Main PID: 7295 (code=exited, status=48)

Apr 18 10:48:18 wekan systemd[1]: snap.wekan.mongodb.service: Service RestartSec=100ms expired, s
Apr 18 10:48:18 wekan systemd[1]: snap.wekan.mongodb.service: Scheduled restart job, restart coun
Apr 18 10:48:18 wekan systemd[1]: Stopped Service for snap application wekan.mongodb.
Apr 18 10:48:18 wekan systemd[1]: snap.wekan.mongodb.service: Start request repeated too quickly.
Apr 18 10:48:18 wekan systemd[1]: snap.wekan.mongodb.service: Failed with result 'exit-code'.
Apr 18 10:48:18 wekan systemd[1]: Failed to start Service for snap application wekan.mongodb.`
 
I'll try reinstalling, but I freshly installed it right before........... still failing :(

Can't say much more about the virtualisation... But I'll ask about the restricted kernels.

**Comment by xet7** [comment]
Wekan does work at Ubuntu x64 at UpCloud, DigitalOcean, AWS, Azure, VirtualBox, VMWare, XEN, KVM, HyperV, Qemu. With 1 GB RAM minimum, 4 GB is better for production.

OVH, Kimsufi and OpenVZ are very problematic, those usually can not run Snap/Docker/Sandstorm. I do not recomment building from source on production servers, because updating source version is time consuming, and outdated software should not be used at Internet. Snap and Sandstorm has automatic updates.

**Comment by xet7** [comment]
I presume you don't have other servers running at those same ports where Wekan runs. By default wekan node is at 3001 and mongodb at 27019.

**Comment by nomomnom** [comment]
So KVM should work for me. There's another snap running on the machine that does work, so snap in general should be working... I also checked the ports. Everything's fine....
![Screenshot (17)](https://user-images.githubusercontent.com/47450088/56363040-8fd7bc80-61eb-11e9-830d-8325a6c010d8.png)

**Comment by xet7** [comment]
Well, KVM works for me, but OVH or Kimsufi could still have some strange settings that restrict something. For me on KVM, when installing Wekan, if there is not anything running at same ports, Wekan snap does start.
